### ISSUE TITLE
Does this ROCm library need to be upgraded to Hawk (HPT) for AMD Ryzen™ 7 8845HS?

### ISSUE THREAD

**Issue by fudingyu** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#8] opened 2024-09-11 06:30 UTC
According to the AMD Ryzen AI official website, the AMD Ryzen 7 8845HS CPU uses Hawk (HPT): AMD Ryzen ™  Instead of the Phoenix (PHX) previously used by 7840HS.

So does the current ROCmLib need to be updated to the Hawk version?

https://ryzenai.docs.amd.com/en/latest/inst.html
Phoenix (PHX): AMD Ryzen™ 7940HS, 7840HS, 7640HS, 7840U, 7640U.
Hawk (HPT): AMD Ryzen™ 8640U, 8640HS, 8645H, 8840U, 8840HS, 8845H, 8945H.
Strix (STX): AMD Ryzen™ Ryzen AI 9 HX370, Ryzen AI 9 365

**Comment by likelovewant** [comment] 2024-09-11 06:59
ROCMLibs ,It's not about the CPU (like Hawk or other versions). This issue is specifically related to your GPU.

**If your GPU is an AMD Radeon RX 780M (gfx1103), then you should be able to use this.**

This repository was created before the release of Hawk (HPT) like the 8840HS.  It uses labels from the earlier "Phoenix"
generation, but you can still use it.

**Comment by fudingyu** [comment] 2024-09-11 08:39
But I can't run it on 8845HS cpu, have a  error="llama runnerprocess has terminated: exit status 0xc0000005" 

https://github.com/likelovewant/ollama-for-amd/issues/16

**Comment by likelovewant** [comment] 2024-09-11 09:26
> But I can't run it on 8845HS cpu, have a error="llama runnerprocess has terminated: exit status 0xc0000005"
> 
> [likelovewant/ollama-for-amd#16](https://github.com/likelovewant/ollama-for-amd/issues/16)

1 , make sure your have enought dedicted vram set in bios , 8g or 16 g.
2,  alway make sure you have updated drivers.
3, HipSDK 6.1.2 , it's not a request. but sometimes , it's helps.

**Comment by fudingyu** [comment] 2024-09-11 09:51
> > But I can't run it on 8845HS cpu, have a error="llama runnerprocess has terminated: exit status 0xc0000005"
> > [likelovewant/ollama-for-amd#16](https://github.com/likelovewant/ollama-for-amd/issues/16)
> 
> 1 , make sure your have enought dedicted vram set in bios , 8g or 16 g. 2, alway make sure you have updated drivers. 3, HipSDK 6.1.2 , it's not a request. but sometimes , it's helps.
> 
> @fudingyu

Thank you for your reply,


According to the running log, vram should be sufficient.

`msg="inference compute" id=0 library=rocm variant="" compute=gfx1103 driver=6.1 name="AMD Radeon 780M Graphics" total="9.0 GiB" available="8.9 GiB"

"" memory.available="[8.9 GiB]" memory.gpu_overhead="0 B" memory.required.full="1.2GiB" memory.required.partial="1.2 GiB" memory.required.kv="96.0 MiB" memory.required.allocations="[1.2 GiB]" memory.weights.total="288.2 MiB" memory.weights.repeating="150.3 MiB" memory.weights.nonrepeating="137.9 MiB" memory.graph.full="298.5 MiB" memory.graph.partial="405.0 MiB"
`


My two computers use the same driver version and are running the same installation package download from https://github.com/likelovewant/ollama-for-amd/releases

**Comment by likelovewant** [comment] 2024-09-11 12:37
> > > But I can't run it on 8845HS cpu, have a error="llama runnerprocess has terminated: exit status 0xc0000005"
> > > [likelovewant/ollama-for-amd#16](https://github.com/likelovewant/ollama-for-amd/issues/16)
> > 
> > 
> > 1 , make sure your have enought dedicted vram set in bios , 8g or 16 g. 2, alway make sure you have updated drivers. 3, HipSDK 6.1.2 , it's not a request. but sometimes , it's helps.
> > @fudingyu
> 
> Thank you for your reply,
> 
> According to the running log, vram should be sufficient.
> 
> `msg="inference compute" id=0 library=rocm variant="" compute=gfx1103 driver=6.1 name="AMD Radeon 780M Graphics" total="9.0 GiB" available="8.9 GiB"
> 
> "" memory.available="[8.9 GiB]" memory.gpu_overhead="0 B" memory.required.full="1.2GiB" memory.required.partial="1.2 GiB" memory.required.kv="96.0 MiB" memory.required.allocations="[1.2 GiB]" memory.weights.total="288.2 MiB" memory.weights.repeating="150.3 MiB" memory.weights.nonrepeating="137.9 MiB" memory.graph.full="298.5 MiB" memory.graph.partial="405.0 MiB" `
> 
> My two computers use the same driver version and are running the same installation package download from https://github.com/likelovewant/ollama-for-amd/releases

 encountered similar issues by someone's local PC due to incorrect settings. Unfortunately, I couldn't reproduce same
error.


Here's a breakdown of how VRAM allocation works and why you might be seeing limited available memory error report (exit status 0xc0000005):

**Understanding VRAM:**

* **Dedicated VRAM:** This is the physical memory specifically allocated to your graphics card.
* **System Memory (RAM):** This is the general memory used by your computer for all tasks.  Windows can sometimes
dynamically allocate some of this RAM as "flexible" VRAM if needed.

**Your Situation:**

* Assume You have 16GB of system memory and `memory.available="[8.9 GiB]"` reported. This suggests you might be using a
significant amount of your system memory for other tasks, leaving less available for flexible VRAM allocation.or using very lower dedicted vram.( check you bios for vram set)
* If you've set your dedicated VRAM to 4GB or lower, Windows might be contributing an additional 4GB-8GB from
system memory to bring your total VRAM up to around 12GB or 11.9GB.

**The "Crash Even with Enough Memory" Issue:**

* Some models have specific requirements for their VRAM usage.
* **Even if your total available memory (including flexible VRAM) appears sufficient, the model might still crash
if it needs to access data beyond its allocated VRAM space.** This can happen even when system memory is
technically available.

**Troubleshooting Steps:**

1. **Try Different Models:** Experiment with models of varying sizes to see if certain ones cause crashes despite
seemingly enough memory.
2. **Increase Dedicated VRAM (If Possible):** If your graphics card allows it ( if not ,[try hack it](https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056) ,had seem someone share this tips on the issue section), try increasing the dedicated VRAM
allocation. This might give the model more direct access to memory.
3. **Close Other Programs:** Free up system memory by closing unnecessary applications before running your models.

if above steps can not help you . 

Here are some potential solutions you could try:

1. **Update Drivers:** Ensure you have the latest drivers installed for your hardware. Sometimes a simple reboot
can also resolve these issues after your update.
2. **Try an Earlier Version:** Downgrade to a previous version of Ollama or the specific model you're using. This
might help identify if the issue is related to a recent update.
3. **Use the ollama Release with ROCmlib Overrides:*https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.6.1.2*
    - Download the latest release from
[https://github.com/ollama/ollama/releases](https://github.com/ollama/ollama/releases).
    - Replace the `rocmlibs` from this repo, use like other compatible gpu arches.
    - Completely close Ollama and open your terminal.
    - Set the environment variable: ` set HSA_OVERRIDE_GFX_VERSION=11.0.3`.
    - Run your desired command (e.g., `ollama run llama3.21`).

4. **Test with Alternative LLMs:**  Try using other LLM clients, such as LM Studio with Vulkan support. If the
issue persists across different tools, it might indicate a problem specific to your local environment.

If all else fails, the issue could stem from conflicting software or settings on your system.

Had see some cases , for gfx803 , by repet try run ` ollama run models name ` , are finaly able to load the models 

Hope this can help your some .

**Comment by fudingyu** [comment] 2024-09-11 16:06
Ok, I found the reason. I copied all these files such as msvcp140.dll into the ‘’ollama-windows-amd64_for_amd\lib\ollama\runners\rocm_v6.1\‘ ’directory, and it can be run. 

It's just strange why this happened.

**Comment by likelovewant** [comment] 2024-09-11 16:07
it's seems that works .Once you have `OllamaSetup .exe` , installed . you may start the server by ` ./ollama serve ` in`ollama-windows-amd64_for_amd` then open another terminal in same location ` ollama run llama3.1`, you don't need to specified the model location as ollama will pick it up by default location.

**Comment by likelovewant** [comment] 2024-09-11 16:11
> Ok, I found the reason. I copied all these files such as msvcp140.dll into the ‘’ollama-windows-amd64_for_amd\lib\ollama\runners\rocm_v6.1\‘ ’directory, and it can be run.
> 
> It's just strange why this happened.

all others files in the compress file are needed as they are dependents by ollama programs.

**Closed** 2024-09-12 14:33 UTC
